### ISSUE TITLE
Incorrect config label texts in Admin

### ISSUE THREAD

**Issue by bleutzinn** [getgrav/grav-plugin-precache#4]
Although the `blueprints.yaml` file in both the dev and master repos here on GitHub are identical and have these labels:
- Plugin status
- Admin enabled
- Log cached pages

in my Admin panel it says:
- Plugin Status
- Plugin Status
- Log Cached Pages

I installed the plugin from within Admin and tried a re-install from Admin. Upon removing the plugin via Admin the plugin all plugin files are deleted from my system (MacOS). I then did a manual install via the GPM. That did not make any difference: the local file `blueprints.yaml` is different from the GitHub repo version. The local file contains the labels as shown in the Admin.

I'm using Grav v1.2.0-rc.3 - Admin v1.3.0-rc.3 but this behaviour dates from earlier. I just never created an issue. It isn't a big issue either but strange it is.

**Comment by rhukster** [comment]
You can just edit the file here in GitHub, it will automatically create a PR.  Much easier than writing an issue for it :)

**Comment by bleutzinn** [comment]
Ah, yes :)
But the point is, the blueprints.yaml file here **is correct**. However for some strange reason it installs a version with different label texts.

**Comment by rhukster** [comment]
I think the issue is the blueprint has been updated in develop just not released.  I'll get a new release out.

**Comment by bleutzinn** [comment]
I doubt that because the master branch has exactly the same blueprints file as the dev branch. Both show correct label texts.

**Comment by rhukster** [comment]
Tag wasn't pushed and blueprint had incorrect version.  I just re-released anyway to make double sure

**Comment by bleutzinn** [comment]
I can confirm, all is well now. Version 1.1.3 installed fine and the correct labels show in Admin.
Thanks!
